# Generated by Django 4.2.4 on 2023-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='', max_length=2000, verbose_name='Dirección de la imagen'),
            preserve_default=False,
        ),
    ]
