# Generated by Django 4.2.4 on 2023-11-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marcas',
        ),
    ]
