# Generated by Django 4.2.4 on 2023-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_marca_options_alter_marca_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='creado',
        ),
        migrations.AddField(
            model_name='categoria',
            name='desc',
            field=models.CharField(default='Descripción de la categoria', max_length=3000, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
