# Generated by Django 4.2.4 on 2023-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_alter_categoria_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Dirección de la imagen'),
        ),
    ]
