# Generated by Django 3.2.23 on 2023-11-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='desc',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(default='Descripción de la marca', max_length=3000, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Inventario.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Inventario.categoria'),
        ),
    ]
