# Generated by Django 3.2.23 on 2023-11-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_auto_20231125_1230'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
    ]
