# Generated by Django 3.2.23 on 2023-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Dirección de la imagen'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Ruta de la imagen'),
        ),
    ]
